name: TodlList CI Practice

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Package build files
        run: 
          zip -r disk.zip disk

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: code-archive
          path: disk.zip
